"use client";

import { useCallback } from "react";
import type { Digest, DigestSection } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Copy, FileDown } from "lucide-react";

export interface DigestViewProps {
  digest: Digest;
  /** Optional class for the container */
  className?: string;
  /** Show action buttons (Copy as Email, Export PDF) */
  showActions?: boolean;
}

function severityStyle(severity: string): string {
  const s = (severity || "").toLowerCase();
  if (s === "critical") return "bg-red-100 text-red-800 border-red-200";
  if (s === "high") return "bg-orange-100 text-orange-800 border-orange-200";
  if (s === "medium") return "bg-amber-100 text-amber-800 border-amber-200";
  return "bg-gray-100 text-gray-700 border-gray-200";
}

function sectionIcon(type: string): string {
  const t = (type || "").toLowerCase();
  if (t === "pricing_changes") return "💰";
  if (t === "new_features") return "⭐";
  if (t === "news") return "📰";
  if (t === "recommendations") return "📋";
  return "•";
}

/** Format digest as plain text for pasting into email */
function digestToEmailText(digest: Digest): string {
  const lines: string[] = [
    `${digest.company_name} — Competitive Intelligence Digest`,
    `Period: ${digest.period}`,
    `Generated: ${digest.generated_at ? new Date(digest.generated_at).toLocaleString() : ""}`,
    "",
    "EXECUTIVE SUMMARY",
    "—".repeat(40),
    digest.executive_summary,
    "",
  ];
  for (const sec of digest.sections) {
    lines.push(sec.title.toUpperCase());
    lines.push("—".repeat(40));
    for (const item of sec.items) {
      const title = (item.title as string) || "Item";
      lines.push(`• ${title}`);
      if (item.description) lines.push(`  ${String(item.description)}`);
      if (item.severity) lines.push(`  [${String(item.severity).toUpperCase()}]`);
      if (item.competitor) lines.push(`  — ${String(item.competitor)}`);
    }
    lines.push("");
  }
  lines.push("—");
  lines.push("This digest was generated by Competitive Intelligence. Do not forward without permission.");
  return lines.join("\n");
}

export function DigestView({ digest, className = "", showActions = true }: DigestViewProps) {
  const handleCopyAsEmail = useCallback(() => {
    const text = digestToEmailText(digest);
    navigator.clipboard.writeText(text).then(() => {
      // Could add toast; for now user sees button state
    });
  }, [digest]);

  const handleExportPdf = useCallback(() => {
    const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
    const sectionsHtml = digest.sections
      .map(
        (sec) =>
          `<div style="margin-top:1.25rem;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">
            <div style="background:#f8fafc;padding:0.75rem 1rem;border-bottom:1px solid #e2e8f0;font-weight:600;color:#0f172a;">${esc(sec.title)}</div>
            <ul style="margin:0;padding:1rem 1.25rem;list-style:disc;">
              ${(sec.items.length ? sec.items : [{ title: "No items in this period.", description: "" }])
                .map(
                  (item) =>
                    `<li style="margin:0.5rem 0;">
                      <strong>${esc(String((item.title as string) || "Item"))}</strong>
                      ${item.severity ? `<span style="margin-left:0.5rem;font-size:0.75rem;padding:0.1rem 0.4rem;border-radius:4px;background:#f1f5f9;color:#475569;">${esc(String(item.severity))}</span>` : ""}
                      ${item.description ? `<p style="margin:0.25rem 0 0;font-size:0.9rem;color:#475569;">${esc(String(item.description))}</p>` : ""}
                      ${item.competitor ? `<p style="margin:0.1rem 0 0;font-size:0.8rem;color:#64748b;">— ${esc(String(item.competitor))}</p>` : ""}
                    </li>`
                )
                .join("")}
            </ul>
          </div>`
      )
      .join("");
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${esc(digest.company_name)} — Digest ${esc(digest.period)}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 700px; margin: 2rem auto; padding: 0 1.5rem; color: #0f172a; }
    .header { border-bottom: 2px solid #1e3a5f; padding-bottom: 1rem; }
    .header h1 { font-size: 1.5rem; margin: 0; }
    .meta { color: #64748b; font-size: 0.875rem; margin-top: 0.5rem; }
    .summary { background: #f1f5f9; padding: 1rem 1.25rem; border-left: 4px solid #1e3a5f; margin: 1rem 0; font-size: 0.95rem; line-height: 1.6; }
  </style>
</head>
<body>
  <div class="header">
    <p style="font-size:0.7rem;text-transform:uppercase;letter-spacing:0.1em;color:#64748b;margin:0;">Competitive Intelligence Briefing</p>
    <h1>${esc(digest.company_name)}</h1>
    <p class="meta">${esc(digest.period)}</p>
    <p class="meta">Generated ${digest.generated_at ? new Date(digest.generated_at).toLocaleString() : ""}</p>
  </div>
  <h2 style="font-size:0.8rem;text-transform:uppercase;color:#475569;margin-top:1.5rem;">Executive Summary</h2>
  <div class="summary">${esc(digest.executive_summary)}</div>
  ${sectionsHtml}
</body>
</html>`;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => {
      win.print();
      win.close();
    }, 400);
  }, [digest]);

  return (
    <div className={className}>
      {showActions && (
        <div className="mb-4 flex flex-wrap items-center gap-2 print:hidden">
          <Button variant="outline" size="sm" onClick={handleCopyAsEmail} className="rounded-lg">
            <Copy className="mr-2 h-4 w-4" />
            Copy as Email
          </Button>
          <Button variant="outline" size="sm" onClick={handleExportPdf} className="rounded-lg">
            <FileDown className="mr-2 h-4 w-4" />
            Export as PDF
          </Button>
        </div>
      )}

      <div className="digest-content space-y-6">
        {/* Header — newsletter style */}
        <div className="border-b-2 border-slate-700 pb-4">
          <p className="text-xs font-semibold uppercase tracking-widest text-slate-500">
            Competitive Intelligence Briefing
          </p>
          <h1 className="mt-1 text-2xl font-bold text-slate-900">
            {digest.company_name}
          </h1>
          <p className="mt-1 text-sm text-slate-600">
            {digest.period}
          </p>
          <p className="mt-1 text-xs text-slate-500">
            Generated {digest.generated_at ? new Date(digest.generated_at).toLocaleString() : ""}
          </p>
        </div>

        {/* Executive summary */}
        <Card className="overflow-hidden rounded-lg border-slate-200 bg-slate-50/50">
          <CardContent className="p-5">
            <h2 className="text-xs font-semibold uppercase tracking-wide text-slate-600">
              Executive Summary
            </h2>
            <p className="mt-2 text-slate-800 leading-relaxed">
              {digest.executive_summary}
            </p>
          </CardContent>
        </Card>

        {/* Sections */}
        {digest.sections.map((section) => (
          <DigestSectionBlock key={section.title} section={section} />
        ))}
      </div>
    </div>
  );
}

function DigestSectionBlock({ section }: { section: DigestSection }) {
  return (
    <Card className="overflow-hidden rounded-lg border-slate-200 shadow-sm">
      <CardContent className="p-0">
        <div className="border-b border-slate-100 bg-slate-50/80 px-4 py-3">
          <span className="mr-2 text-lg" aria-hidden>
            {sectionIcon(section.type)}
          </span>
          <h2 className="inline text-base font-semibold text-slate-900">
            {section.title}
          </h2>
        </div>
        <ul className="divide-y divide-slate-100 p-4">
          {section.items.length === 0 ? (
            <li className="py-2 text-sm text-slate-500">No items in this period.</li>
          ) : (
            section.items.map((item, i) => (
              <li key={i} className="py-3 first:pt-0 last:pb-0">
                <div className="flex flex-wrap items-start gap-2">
                  <span className="font-medium text-slate-900">
                    {(item.title as string) || "Update"}
                  </span>
                  {item.severity && (
                    <span
                      className={`rounded border px-2 py-0.5 text-xs font-medium capitalize ${severityStyle(String(item.severity))}`}
                    >
                      {String(item.severity)}
                    </span>
                  )}
                </div>
                {item.description && (
                  <p className="mt-1 text-sm text-slate-600">
                    {String(item.description)}
                  </p>
                )}
                {item.competitor && (
                  <p className="mt-0.5 text-xs text-slate-500">
                    — {String(item.competitor)}
                  </p>
                )}
              </li>
            ))
          )}
        </ul>
      </CardContent>
    </Card>
  );
}
