"use client";

import { useEffect, useRef, useState } from "react";
import type { SourceAttribution } from "@/lib/types";
import { cn } from "@/lib/utils";
import { Link2, Info } from "lucide-react";

export interface SourceBadgeProps {
  /** When provided, shows full source tooltip. When aiEstimatedOnly is true, source can be minimal. */
  source?: SourceAttribution | null;
  /** Use orange "AI-estimated" style */
  aiEstimated?: boolean;
  /** Show only "AI-estimated" badge (e.g. for KPI cards); source optional */
  aiEstimatedOnly?: boolean;
  className?: string;
}

function formatTimestamp(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString(undefined, {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return iso;
  }
}

function sourceTypeLabel(type: string): string {
  switch (type) {
    case "pricing_page":
      return "Pricing page";
    case "news_page":
      return "News article";
    case "homepage":
      return "Scraped from website";
    case "llm_estimate":
      return "AI-estimated";
    default:
      return type ? String(type).replace(/_/g, " ") : "Scraped from website";
  }
}

export function SourceBadge({ source, aiEstimated, aiEstimatedOnly, className }: SourceBadgeProps) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const isAi = aiEstimatedOnly || aiEstimated || source?.source_type === "llm_estimate";
  const hasSource = source && (source.source_url || source.source_type);

  useEffect(() => {
    if (!open) return;
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("click", handleClick, true);
    return () => document.removeEventListener("click", handleClick, true);
  }, [open]);

  if (!hasSource && !aiEstimatedOnly) return null;

  if (aiEstimatedOnly && !hasSource) {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] font-normal text-amber-600 bg-amber-50",
          className
        )}
        title="This metric is generated by AI from market context."
      >
        <Info className="h-3 w-3 shrink-0" aria-hidden />
        AI-estimated
      </span>
    );
  }

  return (
    <div ref={ref} className={cn("relative inline-flex items-center gap-1", className)}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className={cn(
          "inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] font-normal transition-colors",
          isAi
            ? "text-amber-600 hover:bg-amber-50"
            : "text-gray-500 hover:bg-gray-100 hover:text-gray-700"
        )}
        aria-expanded={open}
        aria-label="View source"
      >
        <Info className="h-3 w-3 shrink-0" aria-hidden />
        <Link2 className="h-3 w-3 shrink-0" aria-hidden />
        <span className="hidden sm:inline">Source</span>
      </button>
      {open && (hasSource || aiEstimatedOnly) && (
        <div
          className="absolute left-0 top-full z-20 mt-1 min-w-[240px] max-w-[320px] rounded-lg border border-gray-200 bg-white p-3 shadow-lg"
          role="dialog"
          aria-label="Source details"
        >
          <p className="text-xs font-medium text-gray-500">
            {hasSource ? sourceTypeLabel(source!.source_type) : "AI-estimated"}
          </p>
          {hasSource && source!.source_url && source!.source_url.startsWith("http") ? (
            <a
              href={source!.source_url}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-1 block break-all text-xs text-blue-600 underline hover:text-blue-700"
            >
              {source!.source_url}
            </a>
          ) : hasSource && source!.source_url ? (
            <p className="mt-1 text-xs text-gray-600">{source!.source_url}</p>
          ) : aiEstimatedOnly ? (
            <p className="mt-1 text-xs text-gray-600">
              This metric is generated by AI from market context and should be independently verified.
            </p>
          ) : null}
          {hasSource && source!.scraped_at && source!.scraped_at.trim() && (
            <p className="mt-1.5 text-[11px] text-gray-400">
              Data collected: {formatTimestamp(source!.scraped_at)}
            </p>
          )}
        </div>
      )}
    </div>
  );
}
